### ISSUE TITLE
Descriptor support

### ISSUE THREAD

**Issue by Jc2k** [detectlabs/aioble#24]
In order to add an asyncio version of HomeKit BLE to home-assistant I need support for descriptors. The current non-asyncio code uses gatt-python and that needed a similar change, the PR is [here](https://github.com/getsenic/gatt-python/pull/36/files) to give you an idea of what the dbus version of the API looks like.

**Comment by kent-williams** [comment]
Hi @Jc2k,

I added descriptor resolution and value read for bluezdbus.

You can find the example [here].(https://github.com/detectlabs/aioble/blob/master/examples/read_descriptors.py)
Just change the device address and run it.

I'll be adding the support to MacOS and Windows, then releasing on PyPi.

-Kent

**Comment by Jc2k** [comment]
Nice one! I can’t wait to try it out!
