### ISSUE TITLE
How does this relate to bleak

### ISSUE THREAD

**Issue by sander76** [detectlabs/aioble#33]
Previously I was playing around with the lib `Bleak` https://github.com/hbldh/bleak
As I hit some roadbumps I went looking for an alternative and ran into this one.
Both are very early stage so neither of them is without its bugs. But as it looks now, I prefer this lib as it gives me more flexibility.

But what strikes me is the similarities. As I went through the code trying to fix bugs it almost must be the case that one is based on the other or they share common source.
Is my feeling correct ? Is the one a hard fork of the other ?

Anyway, thanks for this library !

**Comment by kent-williams** [comment]
Hello @sander76 !

Thanks for your interest! I did in fact adapt some parts from bleak's dotnet implementations as I've noted here https://github.com/detectlabs/UWPBluetoothPython. The corebluetooth and bluezdbus implementations share almost no similarities though as I wanted them to be more python pure.

**Comment by sander76** [comment]
Ah.. all clear !
