### ISSUE TITLE
Connect / disconnect and reconnect failure

### ISSUE THREAD

**Issue by sander76** [detectlabs/aioble#34]
Regarding the dotnet implementation (Not able to check the others yet):
Consider the scenario where you connect to a bt device and this device disconnects from you.

If you then would re-connect using the `connect` command this will fail.
Reason is the actual connection is apparently established in the `discover_services` method here:
https://github.com/detectlabs/aioble/blob/master/aioble/dotnet/device.py#L88

However as this piece of code does not get reached due to this:
https://github.com/detectlabs/aioble/blob/master/aioble/dotnet/device.py#L84

**Comment by kent-williams** [comment]
So the connection actually happens [here](https://github.com/detectlabs/aioble/blob/master/aioble/dotnet/device.py#L47).

If the device disconnects, the C# code is disposing of the object currently, so you must recreate the device object Device(). I will see if there is a way to stop the garbage collector from disposing of it.

**Comment by sander76** [comment]
My assumption is based on this:
https://github.com/hbldh/bleak/blob/master/bleak/backends/dotnet/client.py#L144

I have no knowledge of the underlying C# library.

My situation is as follows:
This client connects to a bt device. Within 3 seconds I need to set a password on this device, otherwise this device connects from this client.
If I then retry the connect method it finishes with success but the password command fails with an error indicating the connection is closed. I did some experimenting and can confirm that if I specifically execute the command here: https://github.com/detectlabs/aioble/blob/master/aioble/dotnet/device.py#L88
The connection is properly established.

However, your mention of recreating the device will work too in my situation I think. And could be the better solution.

**Comment by kent-williams** [comment]
Ok I see, could you show me what you get when the connection retry fails please. I’m curious to see if it’s different from what I’m seeing while attempting to mock your setup.

Also, I’m planning on getting this library in better shape soon, starting with good tests for all three platforms. It was originally created for a much larger project and I moved on once it was working well enough for my needs, but I want to see it fully flushed out for everyone! So please let me know if you feel things are missing or need changing!

**Comment by sander76** [comment]
Here you go:

I first connect to my device:

```
await asyncio.wait_for(self._client.connect(), timeout=10)  # self._client is the aioble Device
await await self._client.discover_services()

# Now I wait for three seconds. This makes my device disconnect. As it requires an incoming command which would set a password.

await asyncio.sleep(3)

# The device is not connected anymore.
# await self._client.is_connected would return False

# Now I will reconnect.
await asyncio.wait_for(self._client.connect(), timeout=10)
await await self._client.discover_services()
await self._client.write_char(<UUID>, pass_command)
```

The last method will now throw an error indicating the object is closed:

```
2019-10-29 09:58:27,747 - asyncio - ERROR - Exception in callback WxAsyncApp.OnTaskCompleted(<Task finishe...t()<---\r\n')>)
handle: <Handle WxAsyncApp.OnTaskCompleted(<Task finishe...t()<---\r\n')>)>
Traceback (most recent call last):
  File "C:\Python37\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\sander\.virtualenvs\ease-programmer-aiWNj2sD\lib\site-packages\wxasync.py", line 76, in OnTaskCompleted
    _res = task.result()
  File "C:\Users\sander\Dropbox\data\aptana\ease-programmer\ease_fabricator\ui\bofu.py", line 30, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\sander\Dropbox\data\aptana\ease-programmer\ease_fabricator\ui\bofu.py", line 96, in connect_and_set_pass
    resp = await self.model.device.connect_and_set_pass()
  File "C:\Users\sander\Dropbox\data\aptana\ease-programmer\ease_fabricator\core\bluetooth_bofu\device.py", line 110, in connect_and_set_pass
    await self._client.start_notify(GATT_NOTIFY_UUID, self._on_notify)
  File "C:\Users\sander\.virtualenvs\ease-programmer-aiWNj2sD\lib\site-packages\aioble\dotnet\device.py", line 176, in start_notify
    self._uwp_bluetooth.StartNotify(characteristic, dotnet_callback), loop=self.loop
  File "C:\Users\sander\.virtualenvs\ease-programmer-aiWNj2sD\lib\site-packages\aioble\dotnet\utils.py", line 12, in wrap_dotnet_task
    raise Exception(task.Exception.ToString())
Exception: System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: The object has been closed. (Exception from HRESULT: 0x80000013)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UWPBluetoothPython.UWPBluetooth.<StartNotify>d__11.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: The object has been closed. (Exception from HRESULT: 0x80000013)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UWPBluetoothPython.UWPBluetooth.<StartNotify>d__11.MoveNext()<---
```

**Comment by sander76** [comment]
But disposing the object and recreating it works just fine. (as a workaround I guess)

**Comment by kent-williams** [comment]
So after looking into this a bit more and getting re-acquainted, I realized that your error behavior is expected. If you look at what happens when a device [disconnects](https://github.com/detectlabs/aioble/blob/master/aioble/dotnet/device.py#L60), we actually dispose of the object intentionally. This behavior makes sense for most ble peripheral connection flow since you really need to scan->find device->connect every time you disconnect since you cannot assume that the device will advertising and ready to connect.

**Comment by sander76** [comment]
Alright. That makes sense. And a bit of rewiring my code based on your suggestion solved my problem already. Thanks.
