### ISSUE TITLE
adopting black as formatter

### ISSUE THREAD

**Issue by sander76** [detectlabs/aioble#36]
Would you consider adopting black as formatter?

**Comment by kent-williams** [comment]
Been meaning to use one, black looks good to me! Feel free to PR this or we can keep this open and I will get to it after the more pressing issues.

**Comment by sander76** [comment]
I am happy to do the PR.
However, it depends a bit on your expectations: I am using PyCharm as my dev environment and haven't found a satisfactory solution of automatically formatting when doing a PR. (Played around with pre-commit but it gave me a lot of headaches

**Comment by kent-williams** [comment]
@sander76 I added a pre-commit with black and flake8 here https://github.com/detectlabs/aioble/pull/37

**Comment by sander76** [comment]
Great !
